package darkhax.classicpack;

import java.util.Arrays;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.enchantment.EnumEnchantmentType;
import net.minecraft.item.Item;
import net.minecraftforge.common.EnumHelper;
import net.minecraftforge.common.MinecraftForge;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import darkhax.classicpack.core.proxy.ClientProxy;
import darkhax.classicpack.core.proxy.CommonProxy;
import darkhax.classicpack.core.utils.Config;
import darkhax.classicpack.core.utils.Reference;
import darkhax.classicpack.items.Items;

@Mod(modid = Reference.MODID, name = Reference.NAME, version = "2.0.0")
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class ClassicPack{

	@SidedProxy(serverSide= Reference.COMMON, clientSide= Reference.CLIENT)
	public static CommonProxy proxy;
	
	@Mod.Instance(Reference.MODID)
    public static ClassicPack instance;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event){	

		getModMeta(event.getModMetadata());
		Config.createConfig(event);
		Items.init();
		ClientProxy.
	}

	@EventHandler
	public void init(FMLInitializationEvent event){

	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event){

	}

	private void getModMeta(ModMetadata meta){

		meta.authorList = Arrays.asList(new String[] { "Darkhax" });
		meta.logoFile = "null";
	    meta.autogenerated = false;
	    meta.credits = "Maintained by Darkhax";
	    meta.description = "This addon pack adds the classic more records to the records mod";
	}
}